// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MimsApi.Data.Context;

#nullable disable

namespace MimsApi.Data.Migrations
{
    [DbContext(typeof(MimsDbContext))]
    partial class MimsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MimsApi.Core.models.Items", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Items", (string)null);
                });

            modelBuilder.Entity("MimsApi.Core.models.PackagingDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ItemsId")
                        .HasColumnType("int");

                    b.Property<int>("PackagingHeaderId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ItemsId")
                        .HasDatabaseName("IX_PackagingDetails_ItemsId");

                    b.HasIndex("PackagingHeaderId")
                        .HasDatabaseName("IX_PackagingDetails_PackagingHeaderId");

                    b.ToTable("PackagingDetails", (string)null);
                });

            modelBuilder.Entity("MimsApi.Core.models.PackagingHeader", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PackagingName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PackagingType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("ParentPackagingId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParentPackagingId")
                        .HasDatabaseName("IX_PackagingHeaders_ParentPackagingId");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("IX_PackagingHeaders_ProductId");

                    b.ToTable("PackagingHeaders", (string)null);
                });

            modelBuilder.Entity("MimsApi.Core.models.Products", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Products", (string)null);
                });

            modelBuilder.Entity("MimsApi.Core.models.Users", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_Email_Unique");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_Username_Unique");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("MimsApi.Core.models.PackagingDetail", b =>
                {
                    b.HasOne("MimsApi.Core.models.Items", "Items")
                        .WithMany("PackagingDetails")
                        .HasForeignKey("ItemsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MimsApi.Core.models.PackagingHeader", "PackagingHeader")
                        .WithMany("PackagingDetails")
                        .HasForeignKey("PackagingHeaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Items");

                    b.Navigation("PackagingHeader");
                });

            modelBuilder.Entity("MimsApi.Core.models.PackagingHeader", b =>
                {
                    b.HasOne("MimsApi.Core.models.PackagingHeader", "ParentPackaging")
                        .WithMany("ChildPackagings")
                        .HasForeignKey("ParentPackagingId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MimsApi.Core.models.Products", "Product")
                        .WithMany("PackagingHeaders")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentPackaging");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("MimsApi.Core.models.Items", b =>
                {
                    b.Navigation("PackagingDetails");
                });

            modelBuilder.Entity("MimsApi.Core.models.PackagingHeader", b =>
                {
                    b.Navigation("ChildPackagings");

                    b.Navigation("PackagingDetails");
                });

            modelBuilder.Entity("MimsApi.Core.models.Products", b =>
                {
                    b.Navigation("PackagingHeaders");
                });
#pragma warning restore 612, 618
        }
    }
}
